<?php

namespace backend\models;

use Yii;
use common\models\myFuncs;
/**
 * This is the model class for table "{{%khoa}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $ngaybatdau
 * @property string $ngayketthuc
 *
 * @property Lopchitiet[] $lopchitiets
 */
class Khoa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%khoa}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name','ngaybatdau'], 'required'],
            [['ngaybatdau', 'ngayketthuc'], 'safe'],
            [['name', 'code'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Tên khóa học'),
            'code' => Yii::t('app', 'code'),
            'ngaybatdau' => Yii::t('app', 'Ngày bắt đầu'),
            'ngayketthuc' => Yii::t('app', 'Ngày kết thúc'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLopchitiets()
    {
        return $this->hasMany(Lopchitiet::className(), ['khoa_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if (isset($this->ngayketthuc))
            $this->ngayketthuc = myFuncs::convertDateSaveIntoDb($this->ngayketthuc);
        if (isset($this->ngaybatdau))
            $this->ngaybatdau = myFuncs::convertDateSaveIntoDb($this->ngaybatdau);
        $this->code = myFuncs::createCode($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
